#ifndef SRC_PORTS_H_
#define SRC_PORTS_H_

#include <CANTalon.h>
#include <VictorSP.h>
#include <Talon.h>
#include <TalonSRX.h>
#include <DoubleSolenoid.h>

#define CLIMBER_MOTOR_TYPE frc::VictorSP
#define SHOOTER_MOTOR_TYPE frc::VictorSP
#define AGITATOR_MOTOR_TYPE frc::VictorSP
#define DRIVETRAIN_MOTOR_TYPE frc::VictorSP

#define GEAR_DOUBLE_SOLENOID_ID  2,5
#define VERSA_DOUBLE_SOLENOID_ID 0,7
#define CLIMBER_DOUBLE_SOLENOID_ID 1,6
#define CLIMBER_MOTOR_ID 3
#define SHOOTER_MOTOR_ID 3
#define AGITATOR_MOTOR_ID 3
#define DRIVETRAIN_MOTOR_LEFT_ID 1,2,3
#define DRIVETRAIN_MOTOR_RIGHT_ID 4,5,6
#define ARDUINO_ID 8

#define CLIMBER_MOTOR new CLIMBER_MOTOR_TYPE(CLIMBER_MOTOR_ID)
#define SHOOTER_MOTOR new SHOOTER_MOTOR_TYPE(SHOOTER_MOTOR_ID)
#define AGITATOR_MOTOR new SHOOTER_MOTOR_TYPE(AGITATOR_MOTOR_ID)

#define MAX_SHOOTER_POWER 0.75

#define ARDUINO_TRAN_DATA_SIZE 4
#define ARDUINO_REC_DATA_SIZE 4

#define ARDUINO_DEBUG 0

#endif
